version: '3'

networks:
  default:
    external:
      name: webproxy

services:
  app:
    image: fuji-crawler
    container_name: fuji-crawler-app
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      - VIRTUAL_HOST=fuji.villevalois.fr
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=fuji.villevalois.fr
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
